### ISSUE TITLE
Unhandled Exception - 'Version string portion was too short or too long. (Parameter 'input')'

### ISSUE THREAD

**Issue by Boldar-Blood** [Drommedhar/DlssUpdater#23]
Encountered an unhandled exception: 
 ```System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at DlssUpdater.Singletons.DllUpdater.IsNewerVersionAvailable(DllType type, InstalledPackage installed) in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Singletons\DllUpdater.cs:line 85
   at DlssUpdater.Defines.GameInfo.<>c__DisplayClass41_0.<GatherInstalledVersions>b__0() in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Defines\GameInfo.cs:line 178
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at DlssUpdater.Defines.GameInfo.GatherInstalledVersions() in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Defines\GameInfo.cs:line 156
   at DlssUpdater.GameLibrary.Steam.SteamLibrary.getGameFromManifest(String path, String appId) in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\GameLibrary\Steam\SteamLibrary.cs:line 182
   at DlssUpdater.GameLibrary.Steam.SteamLibrary.<>c__DisplayClass10_2.<<getGames>b__3>d.MoveNext() in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\GameLibrary\Steam\SteamLibrary.cs:line 132
--- End of stack trace from previous location ---
   at DlssUpdater.GameLibrary.Steam.SteamLibrary.getGames(List`1 folder) in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\GameLibrary\Steam\SteamLibrary.cs:line 145
   at DlssUpdater.GameLibrary.Steam.SteamLibrary.GatherGamesAsync() in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\GameLibrary\Steam\SteamLibrary.cs:line 40
   at DlssUpdater.Singletons.GameContainer.loadGamesAsync() in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Singletons\GameContainer.cs:line 144
   at DlssUpdater.Singletons.GameContainer.LoadGamesAsync() in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Singletons\GameContainer.cs:line 74
   at DlssUpdater.Windows.Splashscreen.Splashscreen.OnContentRendered(EventArgs e) in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Windows\Splashscreen\Splashscreen.xaml.cs:line 168
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by Drommedhar** [comment]
@Boldar-Blood The newest release "2.0.5.2" should fix your issue. Could you check that?

**Comment by Drommedhar** [comment]
@Boldar-Blood Just checking again if you are still experiencing this problem in the newest version?

**Comment by Drommedhar** [comment]
@Boldar-Blood DlssUpdater is now available through the [Microsoft Store](https://apps.microsoft.com/store/detail/9P1NDFBRS95L). Would you please verify to me if you have seen this issue again? If not I will close this issue as there was no answer since over a month.

**Comment by Boldar-Blood** [comment]
Sorry yes, it has been fine since.
________________________________________

Josh
