### ISSUE TITLE
Unhandled Exception - 'Could not find a part of the path 'G:\XboxGames\Like a Dragon- Ishin!\Content\Resources\SplashScreen.png'.'

### ISSUE THREAD

**Issue by Dazog** [Drommedhar/DlssUpdater#24]
Encountered an unhandled exception: 
 ```System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\XboxGames\Like a Dragon- Ishin!\Content\Resources\SplashScreen.png'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at DlssUpdater.Defines.GameInfo.GenerateGameImage() in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Defines\GameInfo.cs:line 226
   at DlssUpdater.Defines.GameConvert.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Defines\GameInfo.cs:line 278
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at DlssUpdater.Singletons.GameContainer.loadGamesAsync() in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Singletons\GameContainer.cs:line 126
   at DlssUpdater.Singletons.GameContainer.LoadGamesAsync() in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Singletons\GameContainer.cs:line 74
   at DlssUpdater.Windows.Splashscreen.Splashscreen.OnContentRendered(EventArgs e) in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Windows\Splashscreen\Splashscreen.xaml.cs:line 168
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by Drommedhar** [comment]
@Dazog The newest release "2.0.5.2" should fix your issue. Could you check that?
