### ISSUE TITLE
Unhandled Exception - 'The process cannot access the file 'C:\Users\colin\Downloads\dlssupdater\installed\DLSS\3.8.10\nvngx_dlss.dll' because it is being used by another process.'

### ISSUE THREAD

**Issue by 0kolym** [Drommedhar/DlssUpdater#31]
Encountered an unhandled exception: 
 ```System.IO.IOException: The process cannot access the file 'C:\Users\colin\Downloads\dlssupdater\installed\DLSS\3.8.10\nvngx_dlss.dll' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at DlssUpdater.Singletons.DllUpdater.DownloadDll(DllType dllType, String version) in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Singletons\DllUpdater.cs:line 186
   at DLSSUpdater.Controls.DownloadButton.doInstall() in D:\a\DlssUpdater\DlssUpdater\DlssUpdater\Controls\DownloadButton.xaml.cs:line 58
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by Drommedhar** [comment]
DlssUpdater is now available through the [Microsoft Store](https://apps.microsoft.com/store/detail/9P1NDFBRS95L) and with that I changed the way deleting a downloaded dll is handled if the signature check failed, which was possibly the reason here.
@0kolym Could you verify with the new version and let me know if you see the issue again?
