### ISSUE TITLE
Unhandled Exception - 'Access to the path 'DLSSUpdater.exe' is denied.'

### ISSUE THREAD

**Issue by Fooughhy** [Drommedhar/DlssUpdater#39]
I have been unable to update this application (using the internal updater) for multiple releases now.
I keep getting the following error after pressing "Ok" when the application finds a new software-update during startup.
Encountered an unhandled exception: 
 ```System.UnauthorizedAccessException: Access to the path 'DLSSUpdater.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at DlssUpdater.Windows.Splashscreen.Splashscreen.OnContentRendered(EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

I have tried running the application ad "Admin", but that doesn't help.

I am running Windows 10, by the way.

Any ideas?

**Comment by Drommedhar** [comment]
Duplicate of #30
